### ISSUE TITLE
It don't generate file when a @import is changed

### ISSUE THREAD

**Issue by asendari** [cakebake/yii2-less.php#3]
Your module don't re-generate css file when a @import file is changed

To reproduce :
File into AppAsset.php : "/css/theme.less" with this content

```
@import "less/variables.less"
@import "less/global.less"
```

You output a correct "/css/theme.css" with good import, but if I change a line into global.css, you don't regenerate the theme.css

I found the line with the issue into AssetConverte.php, it's 61 "if ($resultFilemtime < $assetFilemtime) {" because the $assetFilemtime is older than $resutFilemtime, because we have change a dependent file.

I can bypass this issue by removing this test case but it's not perfect ...

Maybe a parameter into config like "force=>true" can be used into dev environnement to bypass this check

Thanks

**Comment by cakebake** [comment]
This module exists, because I need to combine some Less files WITHOUT `@import`. I don´t parse the less files for import statements to observe them about changes. Sorry.
